#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]


def asset_paths() -> list[pathlib.Path]:
    schemas = sorted((ROOT / "schemas").rglob("*.json"))
    conformance = sorted((ROOT / "conformance").rglob("*.json"))
    if len(schemas) != 21:
        raise RuntimeError(f"expected 21 schema files, found {len(schemas)}")
    if len(conformance) != 53:
        raise RuntimeError(f"expected 53 conformance files, found {len(conformance)}")
    return sorted([ROOT / "PROTOCOL_PIN.json", *schemas, *conformance])


def byte_lines(contents: bytes) -> list[str]:
    values = [f"0x{value:02x}" for value in contents]
    return ["    " + ", ".join(values[index : index + 12]) + "," for index in range(0, len(values), 12)]


def generate() -> str:
    paths = asset_paths()
    lines = [
        "// Generated by scripts/generate_embedded_assets.py. Do not edit.",
        '#include "embedded_assets.hpp"',
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <span>",
        "",
        "namespace missionweaveprotocol::detail {",
        "namespace {",
        "",
        "// clang-format off",
    ]

    for index, path in enumerate(paths):
        contents = path.read_bytes()
        lines.append(f"constexpr std::array<std::uint8_t, {len(contents)}> asset_{index}{{")
        lines.extend(byte_lines(contents))
        lines.append("};")
        lines.append("")

    lines.append(f"constexpr std::array<EmbeddedAsset, {len(paths)}> assets{{{{")
    for index, path in enumerate(paths):
        relative = path.relative_to(ROOT).as_posix()
        lines.append(f'    {{"{relative}", asset_{index}}},')
    lines.extend(
        [
            "}};",
            "// clang-format on",
            "",
            "} // namespace",
            "",
            "std::span<const EmbeddedAsset> embedded_assets() noexcept { return assets; }",
            "",
            "} // namespace missionweaveprotocol::detail",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=ROOT / "src" / "embedded_assets.cpp",
    )
    arguments = parser.parse_args()
    arguments.output.write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    main()
